# Generated by Django 3.2.8 on 2021-10-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makale',
            old_name='yayimlama_tarihi',
            new_name='yayimlanma_tarihi',
        ),
    ]
